from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
import time
 
# ---------------------------------------------------
# LLM
# ---------------------------------------------------
 
llm = ChatOllama(model="qwen2.5:3b", temperature=0, num_predict=512)
 
# ---------------------------------------------------
# Prompt Template
# ---------------------------------------------------
 
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are an expert {domain} engineer. Be concise."),
    ("human", "Explain {topic} with a real-world example.")
])
 
# ---------------------------------------------------
# LCEL Chain
# ---------------------------------------------------
chain = prompt | llm | StrOutputParser()
 
# ---------------------------------------------------
# Invoke
# ---------------------------------------------------
# Invoke is the most basic way to run a chain. You pass
# in the input variables as a dictionary, and get back the output.
result = chain.invoke({
    "domain": "cloud",
    "topic": "microservices"
})
 
print("\n=== INVOKE OUTPUT ===")
print(result)
 
# ---------------------------------------------------
# Stream
# ---------------------------------------------------
# Streaming allows you to get partial results
# as they are generated by the LLM, which can
# be much faster for long responses.
# To create typing effect, you can print each chunk as it arrives.
# Flush is needed to ensure the output is printed immediately without storing it in buffer.
 
print("\n=== STREAM OUTPUT ===")
 
for chunk in chain.stream({
    "domain": "AI",
    "topic": "agents"
}):
    print(chunk, end="", flush=True)
 
print()
 
# ---------------------------------------------------
# Batch
# ---------------------------------------------------
 # IN one call passing multiple inputs to the chain, 
 # and get back multiple results. This is much faster 
 # than invoking the chain multiple times in a loop.

inputs = [
    {
        "domain": "AI",
        "topic": "Machine Learning"
    },
    {
        "domain": "AI",
        "topic": "Deep Learning"
    },
    {
        "domain": "AI",
        "topic": "Reinforcement Learning"
    },
]
 
t0 = time.time()
 
results = chain.batch(inputs)
# Batch returns a list of results, in the same order as the inputs.
# Each result is the output for the corresponding input.
# Runs invoke in parallel 
 
print(f"\nBatch time: {time.time()-t0:.1f}s ({len(results)} results)")
 
for i, r in enumerate(results):
    print(f"\n--- Result {i+1} ---")
    print(r[:120])