#this file defines the Task class, which represents a task in the 
#system with an ID, description, state, and artifacts. 
# It also includes methods to update the task's state and print the 
# new state along with the task ID. 

# The code demonstrates creating a task, updating its state through a
# series of predefined states, and appending an artifact to the task's artifacts list.
import uuid
import time
 
class Task:
    # this class represents a task in the system, with an ID, description, state, and artifacts
    def __init__(self,description):
 
        self.id=str(uuid.uuid4())
 
        self.description=description
 
        self.state="submitted"
 
        self.artifacts=[] #artifacts are the outputs or results generated by the task, such as files or reports

    # this method is called to update the state of the task and print the new state along with the task ID
    def update(self,new_state):
 
        self.state=new_state
 
        print(
            f"{self.id[:8]} -> {new_state}"
        )
 
task=Task(
    "Deploy Payment Service"
)
 
states=[
    "working",
    "input-required",
    "working",
    "completed"
]
 
for state in states:
 
    time.sleep(1)
 
    task.update(state)
 
task.artifacts.append(
    "deployment_report.pdf"
)
 
print(task.artifacts)